# Generated by Django 3.0.8 on 2020-07-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='timestamp',
        ),
    ]
