# Generated by Django 3.0.8 on 2020-07-29 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_remove_update_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
