# Generated by Django 3.0.8 on 2020-07-29 05:06

from django.db import migrations, models
import update.models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_update_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=update.models.updateUpload),
        ),
    ]
